version: '2'
volumes:
    sense-data:
    dashboard-data:
    iaq-data:
services:
  influxdb2:
    restart: always
    #image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    build: ./influx
    volumes:
      - 'sense-data:/var/lib/influxdb'
    ports:
        - '8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=demouser
      - DOCKER_INFLUXDB_INIT_PASSWORD=demouser
      - DOCKER_INFLUXDB_INIT_ORG=influxdb 
      - DOCKER_INFLUXDB_INIT_BUCKET=edge
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=edge
    
  dashboard:
    build: ./dashboard
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
  iaq:
    build: ./iaq
    privileged: true
    restart: always
    volumes:
        - 'iaq-data:/data/my_data'
  connector:
    image: balenablocks/connector
    restart: always
    labels:
      io.balena.features.balena-api: '1'
    privileged: true
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always 
  wifi-connect:
    image: balenablocks/wifi-connect:armv7hf
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    environment:
      PORTAL_LISTENING_PORT: 8080
      ACTIVITY_TIMEOUT: 120
